### ISSUE TITLE
Permanent high CPU usage, slowness and freezes when opening a (very) large repo with zed

### ISSUE THREAD

**Issue by kiriakosv** [zed-industries/community#1669]
### Check for existing issues

- [x] Completed

### Describe the bug / provide steps to reproduce it

When I open a large (mainly) ruby, repository I observe the following:
* A consistent zed CPU usage of over 90%
* General slowness and multiple freezes. The main problem is that it won't even open a file for a while.

These problems occur even if LSP feature is disabled.

### Environment

```
Zed: v0.90.2 (stable)
OS: macOS 13.4.0
Memory: 16 GiB
Architecture: x86_64
```

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

_No response_

**Comment by maxbrunsfeld** [comment]
Thanks for the report, and sorry for the bad experience. Some questions to help diagnose:

* How many git-tracked files are present in your project?

```sh
git ls-files | wc -l
```

* How many total files?

```sh
find . -type f | wc -l
```

* Are there symlinks in the project that point outside of the project?

```sh
while read symlink; do echo $symlink "->" $(readlink "$symlink"); done < <(find . -type l)
````

**Comment by kiriakosv** [comment]
Thanks a lot for your swift response! Regarding your questions:

There are `28517` git tracked files on a total of `204917`. Finally, there are `388` symlinks that point outside of the project. I hope this helps.

**Comment by maxbrunsfeld** [comment]
Ok, thanks for the follow-up @kiriakosv. I'm going to close this one out because I think it is describing the same bug as #1186. Subscribe there for updates. The issue has been fixed on our main branch, and will ship in our stable release next week, I think.

**Comment by kiriakosv** [comment]
Hello, the problem persists in `0.93.4` so the culprit is probably different from #1186.

![Screenshot 2023-07-06 at 3 58 42 PM](https://github.com/zed-industries/community/assets/7139266/66ddd6b4-a928-43de-9a77-fc4f481c3d57)

**Comment by kiriakosv** [comment]
@maxbrunsfeld `0.97.5` solved the problem!
