### ISSUE TITLE
Zed window should remember last window size and position

### ISSUE THREAD

**Issue by ksandvik** [zed-industries/community#414]
### Check for existing issues

- [X] Completed

### Describe the bug

When opening Zed it should remember previous window size and position when Zed was closed.

### To reproduce

1. Open Zed, set expected window size and position.
2. Close Zed.
3. Open Zed again.

### Expected behavior

Expected: previous window size/position is honored.
Now: Using same size and location at startup.

### Environment

Zed 0.49.1 – /Applications/Zed.app \nmacOS 12.5 \narchitecture x86_64

**Comment by mikayla-maki** [comment]
Blocks on: https://github.com/zed-industries/feedback/issues/430

**Comment by rsms** [comment]
+1 — this is going to sound ridiculous, but it's a blocker for adaptation for me as I open a lot of temporary windows in my workflow (currently using Sublime.)

**Comment by iamnbutler** [comment]
> +1 — this is going to sound ridiculous, but it's a blocker for adaptation for me as I open a lot of temporary windows in my workflow (currently using Sublime.)

I don't think it is ridiculous, it is a pain to reset everything up every time.

**Comment by jbergstroem** [comment]
This and a "recent" file menu (#77) is adding a lot of unnecessary friction to just even getting started with your work.

**Comment by benonymus** [comment]
An option to "reopen where left off" (last project and files open from before last close) would also be lovely!

**Comment by emlynmu** [comment]
This was the first thing I noticed when I launched the app. I'm glad to see other people care. The mention of serializable workspaces (#430) makes me worry about it being tied to saving a workspace. I basically only care about the default new window size which I would think would be tied to a new (unsaved) workspace.

**Comment by mikayla-maki** [comment]
Thanks for the behavioral explanation @chriskrycho! :D

**Comment by JosephTLyons** [comment]
This should go out with v0.72.0.

**Comment by chriskrycho** [comment]
I regret to say: This is not quite *fixed* in 0.72.x, though it took a big step forward: It is fixed when *saving workspaces*, and appears to remember the position used for a specific folder, but the feature request here is for a *muuuuuch* more general feature! See e.g. my example above—and note as well that you can trivially reproduce this by just opening any folder and then opening any new window!

**Comment by stjepangolemac** [comment]
If I close Zed while fullscreen it still won't start in fullscreen mode. It would improve consistency if it would remember the mode across restarts.

**Comment by stjepangolemac** [comment]
Bump

**Comment by widersky** [comment]
I think it would be ideal if the **new editor window** had the dimensions of the recently opened project window. Don't like it when a 'clean' window takes up the entire desktop.

**Comment by michealp-coder** [comment]
This is a problem for me as well (running v0.119.16)

I don't have any projects open. When I launch Zed, it's to an empty/blank new file window.

I'll adjust the size and location of the new file window. I then close Zed. 

When I reopen Zed, the window doesn't have the previous size/location of the window and instead reverts to being max width/height of screen.
