### ISSUE TITLE
Docs for `formatter` setting use wrong key

### ISSUE THREAD

**Issue by eth0net** [zed-industries/community#534]
### Check for existing issues

- [X] Completed

### Describe the bug

The docs for the `formatter` field use the key `format_on_save`.

### To reproduce

Open Zed default settings and read to the `formatter` docs (currently lines 47-58).

### Expected behavior

The docs should use the key `formatter`.

### Environment

Zed 0.55.0 – /Applications/Zed.app
macOS 12.6
architecture x86_64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![Screenshot 2022-09-27 at 21 15 14](https://user-images.githubusercontent.com/1347854/192626505-adbea28f-7af4-44f4-b365-2373944f3138.png)

**Comment by jasikpark** [comment]
I believe this is fixed? https://docs.zed.dev/languages/javascript#code-formatting

**Comment by eth0net** [comment]
Still looks the same, that link is unrelated. Open Zed and go to the default settings using the palette, mine still shows as above. The doc comments for `formatter` only refer to `format_on_save` which is above, perhaps they're in the wrong order or something.

**Comment by jasikpark** [comment]
ah, I see, maybe the issue title could be `Doc comments in Default Settings shows "formatter_on_save" instead of "formatter" for the "formatter" config option`

wait that's too long 😓 

but I think "doc comments" is clearer - i thought you meant the online docs :p
